version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: ./docker-entrypoint.sh

  # the database url should have this name
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - ./samiptterdb:/data/db
volumes:
  samiptter:
