export const TWEET_LIST_REQUEST = "TWEET_LIST_REQUEST";
export const TWEET_LIST_SUCCESS = "TWEET_LIST_SUCCESS";
export const TWEET_LIST_FAIL = "TWEET_LIST_FAIL";
export const TWEET_LIST_RESET = "TWEET_LIST_RESET";

export const TWEET_DETAILS_REQUEST = "TWEET_DETAILS_REQUEST";
export const TWEET_DETAILS_SUCCESS = "TWEET_DETAILS_SUCCESS";
export const TWEET_DETAILS_FAIL = "TWEET_DETAILS_FAIL";
export const TWEET_DETAILS_RESET = "TWEET_DETAILS_RESET";

export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST";
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS";
export const CREATE_TWEET_FAIL = "CREATE_TWEET_FAIL";

export const DELETE_TWEET_REQUEST = "DELETE_TWEET_REQUEST";
export const DELETE_TWEET_SUCCESS = "DELETE_TWEET_SUCCESS";
export const DELETE_TWEET_FAIL = "DELETE_TWEET_FAIL";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
