export const TWEET_LIST_REQUEST = "TWEET_LIST_REQUEST";
export const TWEET_LIST_SUCCESS = "TWEET_LIST_SUCCESS";
export const TWEET_LIST_FAIL = "TWEET_LIST_FAIL";

export const TWEET_DETAILS_REQUEST = "TWEET_DETAILS_REQUEST";
export const TWEET_DETAILS_SUCCESS = "TWEET_DETAILS_SUCCESS";
export const TWEET_DETAILS_FAIL = "TWEET_DETAILS_FAIL";
export const TWEET_DETAILS_RESET = "TWEET_DETAILS_RESET";

export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST";
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS";
export const CREATE_TWEET_FAIL = "CREATE_TWEET_FAIL";

// export const TWEET_LIKE_REQUEST = "TWEET_LIKE_REQUEST";
// export const TWEET_LIKE_SUCCESS = "TWEET_LIKE_SUCCESS";
// export const TWEET_LIKE_FAIL = "TWEET_LIKE_FAIL";
