export const TWEET_LIST_REQUEST = "TWEET_LIST_REQUEST";
export const TWEET_LIST_SUCCESS = "TWEET_LIST_SUCCESS";
export const TWEET_LIST_FAIL = "TWEET_LIST_FAIL";

export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST";
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS";
export const CREATE_TWEET_FAIL = "CREATE_TWEET_FAIL";
