export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";
export const EDIT_PROFILE_RESET = "EDIT_PROFILE_RESET";

export const LIST_USERS_REQUEST = "LIST_USERS_REQUEST";
export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESS";
export const LIST_USERS_FAIL = "LIST_USERS_FAIL";
export const LIST_USERS_RESET = "LIST_USERS_RESET";

export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAIL = "ADD_FRIEND_FAIL";

export const GET_RECOMMENDED_USERS_REQUEST = "GET_RECOMMENDED_USERS_REQUEST";
export const GET_RECOMMENDED_USERS_SUCCESS = "GET_RECOMMENDED_USERS_SUCCESS";
export const GET_RECOMMENDED_USERS_FAIL = "GET_RECOMMENDED_USERS_FAIL";

export const TOGGLE_VERIFY_REQUEST = "TOGGLE_VERIFY_REQUEST";
export const TOGGLE_VERIFY_SUCCESS = "TOGGLE_VERIFY_SUCCESS";
export const TOGGLE_VERIFY_FAIL = "TOGGLE_VERIFY_FAIL";
export const TOGGLE_VERIFY_RESET = "TOGGLE_VERIFY_RESET";
